baseURL: 'https://dswij.com'
languageCode: 'en-us'
title: 'dswij'
theme: "PaperMod"

menu:
  main:
    - name: Contact me
      url: contact/
      weight: 10
    - name: Acknowledgement
      url: ack/
      weight: 1

params:
  homeInfoParams:
    Content: |
      dswij's personal blog

markup:
  goldmark:
    renderer:
      unsafe: true
