baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'dswij'
theme: "PaperMod"

params:
  homeInfoParams:
    Content: >
      Hello, this is mostly my personal notes and commentaries on my thoughts that I decided to jot down.
      Hopefully, you might find something interesting here.
